# Generated by Django 5.1.1 on 2024-09-21 15:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_messages_content_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
