# Generated by Django 5.1.1 on 2024-09-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_messages_sent_interacted_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=12),
        ),
    ]
