# Generated by Django 5.1.1 on 2024-09-26 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_campaign_ip_address_campaign_status'),
        ('mail', '0005_remove_emailaccounts_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.emailaccounts'),
        ),
    ]
