# Generated by Django 5.0.3 on 2024-09-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailaccounts',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='emailaudience',
            name='tag',
            field=models.CharField(default='', max_length=30),
        ),
    ]
