# Generated by Django 5.0.3 on 2024-09-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_emailaccounts_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailclientdata',
            name='tag',
            field=models.CharField(default='', max_length=30),
        ),
    ]
