# Generated by Django 5.1.1 on 2024-09-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_emailaccounts_smtp_port_emailaccounts_smtp_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccounts',
            name='is_active',
        ),
    ]
